[build-system]
requires = [
    "python_version>='3.7'",
    "setuptools",
    "wheel",
    "Cython>=0.27",
]

[tool.black]
line-length = 120
target-version = ['py37', 'py38']
exclude = ".*/tests/cpython/.*"
