version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # - python/load-cache
      # - python/install-deps
      # - python/save-cache
      - run: make ci

workflows:
  main:
    jobs:
      - build-and-test
