version: '2'

# Not all are default.
services:

  omnibus-dynamodb:
    build: '.'
    image: 'wrmsr/omnibus-dynamodb:latest'
    restart: 'unless-stopped'
    expose:
      - '8000'
    ports:
      - '22211:8000'

  omnibus-elasticmq:
    build: '.'
    image: 'wrmsr/omnibus-elasticmq:latest'
    restart: 'unless-stopped'
    expose:
      - '9324'
    ports:
      - '22212:9324'

  omnibus-elasticsearch:
    build: '.'
    image: 'wrmsr/omnibus-elasticsearch:latest'
    restart: 'unless-stopped'
    environment:
      ES_JAVA_OPTS: '-Xms750m -Xmx750m'
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
    expose:
      - '9200'
    ports:
      - '22213:9200'

  omnibus-kafka:
    build: '.'
    image: 'wrmsr/omnibus-kafka:latest'
    restart: 'unless-stopped'
    hostname: 'omnibus-kafka'
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_DOCKER_INTERNAL://omnibus-kafka:19092,LISTENER_DOCKER_EXTERNAL://127.0.0.1:22214'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_DOCKER_INTERNAL'
      KAFKA_ZOOKEEPER_CONNECT: 'omnibus-zookeeper:2181'
      KAFKA_BROKER_ID: '1'
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
    depends_on:
      - 'omnibus-zookeeper'
    expose:
      - '22214'
    ports:
      - '22214:22214'

  omnibus-memcached:
    build: '.'
    image: 'wrmsr/omnibus-memcached:latest'
    restart: 'unless-stopped'
    expose:
      - '11211'
    ports:
      - '22215:11211'

  omnibus-minio:
    build: '.'
    image: 'wrmsr/omnibus-minio:latest'
    restart: 'unless-stopped'
    environment:
      MINIO_ACCESS_KEY: 'AKIAIOSFODNN7EXAMPLE'
      MINIO_SECRET_KEY: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
    expose:
      - '9000'
    ports:
      - '22216:9000'

  omnibus-mongo:
    build: '.'
    image: 'wrmsr/omnibus-mongo:latest'
    restart: 'unless-stopped'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'omnibus'
    expose:
      - '27017'
    ports:
      - '22217:27017'

  omnibus-mysql-master:
    build: '.'
    image: 'wrmsr/omnibus-mysql:latest'
    restart: 'unless-stopped'
    environment:
      MYSQL_USER: 'omnibus'
      MYSQL_PASSWORD: 'omnibus'
      MYSQL_ROOT_PASSWORD: 'omnibus'
    expose:
      - '3306'
    ports:
      - '22218:3306'

  omnibus-mysql-slave:
    build: '.'
    image: 'wrmsr/omnibus-mysql:latest'
    restart: 'unless-stopped'
    environment:
      MYSQL_USER: 'omnibus'
      MYSQL_PASSWORD: 'omnibus'
      MYSQL_ROOT_PASSWORD: 'omnibus'
      REPLICATE_FROM: 'omnibus-mysql-master'
    links:
      - 'omnibus-mysql-master'
    depends_on:
      - 'omnibus-mysql-master'
    expose:
      - '3306'
    ports:
      - '22219:3306'

  omnibus-postgres-master:
    build: '.'
    image: 'wrmsr/omnibus-postgres:latest'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: 'omnibus'
      POSTGRES_PASSWORD: 'omnibus'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    expose:
      - '5432'
    ports:
      - '22220:5432'

  omnibus-postgres-slave:
    build: '.'
    image: 'wrmsr/omnibus-postgres:latest'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: 'omnibus'
      POSTGRES_PASSWORD: 'omnibus'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: 'omnibus-postgres-master'
    links:
      - 'omnibus-postgres-master'
    depends_on:
      - 'omnibus-postgres-master'
    expose:
      - '5432'
    ports:
      - '22221:5432'

  omnibus-redis:
    build: '.'
    image: 'wrmsr/omnibus-redis:latest'
    restart: 'unless-stopped'
    expose:
      - '6379'
    ports:
      - '22222:6379'

  omnibus-spark-master:
    build: '.'
    image: 'wrmsr/omnibus-spark-master:latest'
    restart: 'unless-stopped'
    environment:
      - 'INIT_DAEMON_STEP=setup_spark'
      - 'constraint:node==omnibus-spark-master'
    ports:
      - '22223:8080'
      - '22224:7077'

  omnibus-spark-worker:
    build: '.'
    image: 'wrmsr/omnibus-spark-worker:latest'
    restart: 'unless-stopped'
    environment:
      - 'SPARK_MASTER=spark://omnibus-spark-master:7077'
      - 'constraint:node==omnibus-spark-worker'
    links:
      - 'omnibus-spark-master'
    depends_on:
      - 'omnibus-spark-master'
    ports:
      - '22225:8081'

  omnibus-zookeeper:
    image: 'wrmsr/omnibus-zookeeper:latest'
    hostname: 'omnibus-zookeeper'
    environment:
      ZOO_MY_ID: '1'
      ZOO_PORT: '2181'
      ZOO_SERVERS: 'server.1=0.0.0.0:2888:3888;2181'
    expose:
      - '2181'
    ports:
      - '22226:2181'

  omnibus-dev:
    build: '.'
    image: 'wrmsr/omnibus-dev:latest'
    restart: 'unless-stopped'
    cap_add:
      - 'SYS_PTRACE'
    security_opt:
      - 'apparmor:unconfined'
    volumes:
      - '..:/omnibus'
    depends_on:
      - 'omnibus-mysql-master'
      - 'omnibus-mysql-slave'
      - 'omnibus-postgres-master'
      - 'omnibus-postgres-slave'
      - 'omnibus-redis'
    links:
      - 'omnibus-mysql-master'
      - 'omnibus-mysql-slave'
      - 'omnibus-postgres-master'
      - 'omnibus-postgres-slave'
      - 'omnibus-redis'
    expose:
      - '8000'
    ports:
      - '22210:8000'
