name: Ci

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

env:
  IMAGE_NAME: 'omnibus-ci'

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - uses: 'styfle/cancel-workflow-action@0.4.1'
        with:
          access_token: '${{ github.token }}'

      - name: 'Cache'
        uses: 'actions/cache@v2'
        with:
          path: '~/.cache'
          key: 'omnibus-ci-${{ github.sha }}'
          restore-keys: |
            omnibus-ci-${{ github.ref }}

      - name: 'Docker cache load'
        run: >
          tar -tvf docker image history wrmsr/omnibus-ci ;
          docker load -i ~/.cache/docker/omnibus-ci.tar ||:

      - name: 'Docker ls images'
        run: >
          docker images -a ;
          docker image history wrmsr/omnibus-ci ||: ;

      # - uses: 'mxschmitt/action-tmate@v2'

      - name: 'Run tests'
        run: >
          OMNIBUS_CI_DOCKER_OPTS='-v ${{ github.workspace }}:/github/workspace'
          OMNIBUS_CI_OUTPUT_DIR=/github/workspace
          make ci

      - name: 'Docker ls images'
        run: >
          docker images -a ;
          docker image history wrmsr/omnibus-ci ;

      - name: 'Docker cache save'
        run: >
          mkdir -p ~/.cache/docker/ &&
          docker save -o ~/.cache/docker/omnibus-ci.tar wrmsr/omnibus-ci

      - uses: 'ashley-taylor/junit-report-annotations-action@1.3'
        if: '${{ always() }}'
        with:
          access-token: '${{ github.token }}'
          path: 'test-results.xml'
