name: Ci

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

env:
  IMAGE_NAME: 'omnibus-ci'

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - uses: 'styfle/cancel-workflow-action@0.4.1'
        with:
          access_token: '${{ github.token }}'

      - name: 'Cache'
        uses: 'actions/cache@v2'
        with:
          path: '~/.cache'
          key: 'omnibus-ci'

      - name: 'Docker cache'
        run: 'find ~/.cache'

      - name: 'Docker cache'
        run: >
          docker load -i ~/.cache/docker/omnibus-ci.tar

        # if [ -f "~/.cache/docker/omnibus-ci.tar" ] ; then
        #   docker load -i ~/.cache/docker/omnibus-ci.tar ;
        # fi

      # - uses: 'mxschmitt/action-tmate@v2'

      - name: 'Run tests'
        run: >
          OMNIBUS_CI_DOCKER_OPTS='-v ${{ github.workspace }}:/github/workspace'
          OMNIBUS_CI_OUTPUT_DIR=/github/workspace
          make ci

      - name: 'Docker cache'
        run: >
          mkdir -p ~/.cache/docker/ &&
          docker save -o ~/.cache/docker/omnibus-ci.tar wrmsr/omnibus-ci

      - uses: 'ashley-taylor/junit-report-annotations-action@1.3'
        if: '${{ always() }}'
        with:
          access-token: '${{ github.token }}'
          path: 'test-results.xml'
