name: Ci

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

env:
  IMAGE_NAME: 'omnibus-ci'

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - uses: 'styfle/cancel-workflow-action@0.4.1'
        with:
          access_token: '${{ github.token }}'

      # - uses: 'mxschmitt/action-tmate@v2'

      - name: 'Pull images'
        run: 'make ci-pull'

      - uses: 'satackey/action-docker-layer-caching@v0.0.4'

      - name: 'Run tests'
        run: 'make ci'

      - uses: 'ashley-taylor/junit-report-annotations-action@1.3'
        if: '${{ always() }}'
        with:
          access-token: '${{ github.token }}'
          path: 'test-*.xml'
